W5D1/RedditRails/config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:create, :new]

  resource :session, only: [:new, :create, :destroy]

  resources :subs do
    resource :posts, only: [:new]
  end

  resources :posts, except: [:new, :index] do
    resources :comments, only: [:new]
    resources :votes, only: [:create]
  end

  resources :comments, only: [:create, :show] do
    resources :votes, only: [:create]
  end



  root :to => 'subs#index'
end

W5D1/RedditRails/app/models/sub.rb
# == Schema Information
#
# Table name: subs
#
#  id           :integer          not null, primary key
#  title        :string           not null
#  description  :string           not null
#  moderator_id :integer          not null
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#

class Sub < ActiveRecord::Base
  validates :title, :description, :moderator, presence: true

  belongs_to :moderator,
    class_name: :User,
    foreign_key: :moderator_id

  has_many :post_subs

  has_many :posts,
    through: :post_subs,
    source: :post
end

W5D1/RedditRails/app/controllers/subs_controller.rb
class SubsController < ApplicationController
  before_action :require_logged_in
  before_action :check_if_moderator, only: [:edit, :update]

  def index
    @subs = Sub.all
    render :index
  end

  def new
    @sub = Sub.new
      render :new
  end

  def show
    @sub = Sub.find(params[:id])
    @sub.posts.includes(:title)
    render :show
  end

  def create
    s = Sub.new(sub_params)
    s.moderator = current_user
    if s.save
      redirect_to sub_url(s)
    else
      flash.now[:errors] = s.errors.full_messages
      render :new
    end
  end

  def edit
    @sub = Sub.find(params[:id])
      render :edit
  end

  def update
    s = Sub.find(params[:id])
    if s.update(sub_params)
      redirect_to sub_url(s)
    else
      flash[:errors] = s.errors.full_messages
      redirect_to edit_sub_url(s)
    end
  end

  def check_if_moderator
    unless current_user == Sub.find(params[:id]).moderator
      flash[:errors] = "you must be the mod"
      redirect_to sub_url(params[:id])
    end
  end

  private
  def sub_params
    params.require(:sub).permit(:description, :title)
  end
end

W5D1/RedditRails/app/helpers/subs_helper.rb
module SubsHelper
end

W5D1/RedditRails/app/views/subs/_form.html.erb
<% action_url = sub.persisted? ? sub_url(sub) : subs_url %>
<% method_verb = sub.persisted? ? "PATCH" : "POST" %>
<% flavor_text = sub.persisted? ? "Edit sub!" : "Create sub!" %>

<h1><%= flavor_text %></h1>
<form  action="<%= action_url %>" method="post">
  <input type="hidden" name="_method" value="<%= method_verb %>">
  <%= auth_token %>

  <label for="title">Title</label>
  <input type="text" name="sub[title]" id="title" value="<%= sub.title %>">
  <br><br>

  <label for="descrition">Description</label>
  <br>
  <textarea name="sub[description]" rows="8" cols="40" id="description" ><%= sub.description %></textarea>
  <br>

  <input type="submit" value=" <%=flavor_text %>">
</form>

W5D1/RedditRails/app/views/subs/edit.html.erb
<%= render "form", sub: @sub %>

W5D1/RedditRails/app/views/subs/index.html.erb
<h1>all the subs!</h1>

<% @subs.each do |sub| %>
<a href="<%= sub_url(sub) %>"><%= sub.title %></a><br>
<% end %>
<br><br>

<a href="<%= new_sub_url %>">new subReddit</a>

W5D1/RedditRails/app/views/subs/new.html.erb
<%= render "form", sub: @sub %>

W5D1/RedditRails/app/views/subs/show.html.erb
<br><br>
<h1><%= @sub.title %></h1>
<br><br>
<%= @sub.description %>
<br><br>
<a href="<%= new_sub_posts_url(@sub) %>">Create a post!</a>
<br>
<% if current_user == @sub.moderator %>
<a href="<%= edit_sub_url %>">Edit this sub</a>
<% end %>
<ol>
  <% @sub.posts.each do |post| %>
    <li> <a href="<%= post_url(post) %>"><%= post.title %></a></li>
  <% end %>
</ol>

<a href="<%= subs_url %>">back to front page</a>