W5D1/RedditRails/config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:create, :new]

  resource :session, only: [:new, :create, :destroy]

  resources :subs do
    resource :posts, only: [:new]
  end

  resources :posts, except: [:new, :index] do
    resources :comments, only: [:new]
    resources :votes, only: [:create]
  end

  resources :comments, only: [:create, :show] do
    resources :votes, only: [:create]
  end



  root :to => 'subs#index'
end

W5D1/RedditRails/app/models/comment.rb
# == Schema Information
#
# Table name: comments
#
#  id                :integer          not null, primary key
#  content           :text             not null
#  author_id         :integer          not null
#  post_id           :integer          not null
#  parent_comment_id :integer
#  created_at        :datetime         not null
#  updated_at        :datetime         not null
#

class Comment < ActiveRecord::Base
  validates :content, :user, :post, presence: true

  belongs_to :user,
    foreign_key: :author_id,
    class_name: :User

  belongs_to :post

  has_many :child_comments,
    class_name: :Comment,
    primary_key: :id,
    foreign_key: :parent_comment_id

  has_many :votes, as: :votable

  def score
    votes.select("SUM(value)").pluck("SUM(value)")
  end
end

W5D1/RedditRails/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @post_id = params[:post_id]
    render :new
  end

  def create
    comment = Comment.new(comment_params)
    comment.user = current_user
    if comment.save
      redirect_to post_url(comment.post)
    else
      flash[:errors] = comment.errors.full_messages
      redirect_to post_url(comment.post)
    end
  end

  def show
    @comment = Comment.find(params[:id])
    render :show
  end

  private
  def comment_params
    params.require(:comment).permit(:content, :post_id, :parent_comment_id)
  end
end

W5D1/RedditRails/app/helpers/comments_helper.rb
module CommentsHelper
end

W5D1/RedditRails/app/views/comments/new.html.erb
<h1>Add comment below</h1>
<form action="<%= comments_url %>" method="post">
  <%= auth_token %>
  <input type="hidden" name="comment[post_id]" value="<%= @post_id %>">
  <textarea name="comment[content]" rows="8" cols="40"></textarea><br>
  <input type="submit" name="name" value="post me">
</form>

W5D1/RedditRails/app/views/comments/show.html.erb
<h1>Comments page</h1>
<%= @comment.content %>
<form action="<%= comment_votes_url(@comment) %>" method="post">
  <%= auth_token %>
  <input type="hidden" name="vote[votable_id]" value="<%= @comment.id %>">
  <input type="hidden" name="vote[votable_type]" value="<%= @comment.class %>">
  <input type="hidden" name="vote[value]" value= 1>
  <input type="submit" value="👍">
</form>
<form action="<%= comment_votes_url(@comment) %>" method="post">
  <%= auth_token %>
  <input type="hidden" name="vote[votable_id]" value="<%= @comment.id %>">
  <input type="hidden" name="vote[votable_type]" value="<%= @comment.class %>">
  <input type="hidden" name="vote[value]" value= -1>
  <input type="submit" value="👎">
</form>
<br><br>
<h2>Replies</h2>
<% @comment.child_comments.each do |child| %>
  <%= child.content %>
  <br>
<% end %>
<h3>Reply to this thread</h3>
  <form action="<%= comments_url %>" method="post">
    <%= auth_token %>
    <input type="hidden" name="comment[parent_comment_id]" value="<%= @comment.id %>">
    <textarea name="comment[content]" rows="8" cols="40"></textarea>
    <br>
    <input type="hidden" name="comment[post_id]" value="<%= @comment.post_id %>">
    <input type="hidden" name="comment[parent_comment_id]" value="<%= @comment.id %>">
    <input type="submit" name="name" value="Post reply">
  </form>